name: guitarduets
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ffmpeg>=4.2
  - pytorch>=2.1
  - torchaudio>=2.1
  - pytorch-cuda=11.8
  - tqdm
  - pip
  - pip:
    - asteroid
    - einops
    - julius>=0.2.3
    - matplotlib
    - mido
    - museval>=0.4.0
    - "numpy<2"
    - omegaconf
    - openunmix
    - pandas
    - PyYAML
    - scipy
    - soundfile
    - threadpoolctl
    - ipykernel
    - ipywidgets
    - librosa
    - -e .
