name: guitarrecordings
splits:
  train: /home/frederic/Documents/UPF/semester2/MIR/guitar-duets-source-separation/GuitarDuets/Synth
  valid: /home/frederic/Documents/UPF/semester2/MIR/guitar-duets-source-separation/GuitarDuets/Real/test
  test: /home/frederic/Documents/UPF/semester2/MIR/guitar-duets-source-separation/GuitarDuets/Real/test
manifest_output: data/manifests/guitarrecordings.json

